name 'evenup-graphite_reporter'
version '0.2.0'
license 'Apache 2.0'
summary 'Report processor that sends metrics to graphite'
project_page 'https://github.com/evenup/evenup-graphite_reporter'
author 'Justin Lambert <jlambert@letsevenup.com>'
